### ISSUE TITLE
Implement JWT in our example todo apps

### ISSUE THREAD

**Issue by borsi** [SenseNet/sn-client-js#21]
# App checklist

- [ ] react example todo app
- [ ] vue.js example todo app
- [ ] angular (dani's) example todo app
- [ ] angular2 example todo app
- [ ] aurelia (bedizoli's) example todo app

**Comment by B3zo0** [comment]
- [x] aurelia https://github.com/B3zo0/sn7-aurelia-redux-todo-app
