### ISSUE TITLE
Reference field common tasks

### ISSUE THREAD

**Issue by borsi** [SenseNet/sn-client-js#31]
## Tasks:
- [x] My nice silky Loading
  - [x] The main control needs to know what to load
- [x] Mapping extension for the reference field
- [x] Search in references in client-js
- [x] Weave it through the redux layer

**Comment by gallayl** [comment]
Search in references - related to https://github.com/SenseNet/sn-client-js/issues/38
