### ISSUE TITLE
"Order by" type cannot be specified at field level

### ISSUE THREAD

**Issue by borsi** [SenseNet/sn-client-js#59]
As a developer, I'd like to be able to specify whether my query should return with the result set in an ascending or a descending order.

## Tasks
- [x] Extend the query builder API
- [x] Test and deploy (seek and destroy)

## Acceptance crit
- [x] I can specify the ordering by asc or desc

**Comment by gallayl** [comment]
Usage example for extended ordering:
``` ts
const params = {
   orderby: [
      ['CreationDate', 'desc'],
      'Name',
      'DisplayName'
   ]
}
```
